EpamProject/EpamProject.WEB/Controllers/CityController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using EpamProject.DAL.Entities;
using EpamProject.BLL.Interfaces;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using EpamProject.WEB.Models.CityViewModels;
using EpamProject.BLL;
using Sakura.AspNetCore;

namespace EpamProject.WEB.Controllers
{
    [Authorize(Roles = "Administrator, Moderator")]
    public class CityController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ICityService _cityService;

        public CityController(
           ICityService cityService,
           UserManager<ApplicationUser> userManager,
           SignInManager<ApplicationUser> signInManager,
           RoleManager<IdentityRole> roleManager)
        {
            _cityService = cityService;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult ListCities(int page = Constants.PageDefault)
        {
            var data = _cityService.GetAll().ToList();
            if (data == null)
                return NotFound();

            var pagedData = data.ToPagedList(Constants.PageSize, page);
            return View(pagedData);
        }

        [HttpGet]
        public IActionResult AddCity()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddCity(UpdateCityModel model)
        {
            if (ModelState.IsValid)
            {
                var data = _cityService.GetByName(model.Name);
                if (data != null)
                {
                    ModelState.AddModelError("Name", "This name already exists");
                    return View(model);
                }

                data = new City
                {
                    Name = model.Name
                };
                
                _cityService.Create(data);
                return RedirectToAction("profile", "manage");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult EditCity(int cityId)
        {
            var data = _cityService.GetById(cityId);
            if (data == null)
                return NotFound();

            var model = new UpdateCityModel
            {
                Id = data.Id,
                Name = data.Name
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCity(UpdateCityModel model)
        {
            if (ModelState.IsValid)
            {
                var data = _cityService.GetById(model.Id);
                if (data == null)
                    return NotFound();

                if (_cityService.GetByName(model.Name) != null)
                {
                    ModelState.AddModelError("Name", "This name already exists");
                    return View(model);
                }

                data.Name = model.Name;

                _cityService.Update(data);
                return RedirectToAction("profile", "manage");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult RemoveCity(int cityId)
        {
            var user = GetCurrentUserAsync();
            if (user.Result == null)
                return RedirectToAction("logoff", "account");

            var data = _cityService.GetById(cityId); 
            if (data == null)
                return NotFound();

            if (data.Venues == null)
            {
                _cityService.Remove(data);
                return RedirectToAction("listcities", "city");
            }
            else if (data.Venues.Count == 0)
            {
                _cityService.Remove(data);
                return RedirectToAction("listcities", "city");
            }
            else
                return NotFound("Deleting is not possible, there are venues for this city");
        }

        #region Helpers

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }

        #endregion
    }
}

EpamProject/EpamProject.WEB/Views/City/AddCity.cshtml
@model UpdateCityModel

@{
    ViewData["Title"] = @Localizer["city addition"];
}

<ol class="breadcrumb">
    <li><a href="@Url.Action("profile", "manage")" class="text-capitalize">@Localizer["profile"]</a></li>
    <li><a href="@Url.Action("listcities", "city")" class="text-capitalize">@Localizer["list of cities"]</a></li>
    <li class="active text-capitalize">@Localizer["city addition"]</li>
</ol>

<section class="addrecord_s">
    <div class="container">
        <div class="row">
            <h4 class="text-center text-capitalize">@Localizer["city addition"]</h4>
        </div>
        <div class="row">
            <form asp-controller="City" asp-action="AddCity" method="post" asp-antiforgery="true">
                <div class="col-md-12">
                    <div class="form-group">
                        <h5 class="text-capitalize"><label asp-for="Name"></label></h5>
                        <input type="text" class="form-control" asp-for="Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-default my_btn text-capitalize">@Localizer["submit"]</button>
                </div>
            </form>
        </div>
    </div>
</section>

@section Scripts
{
    <script src="~/js/city.js" asp-append-version="true"></script>
}

EpamProject/EpamProject.WEB/Views/City/EditCity.cshtml
@model UpdateCityModel

@{
    ViewData["Title"] = @Localizer["city editing"];
}

<ol class="breadcrumb">
    <li><a href="@Url.Action("profile", "manage")" class="text-capitalize">@Localizer["profile"]</a></li>
    <li><a href="@Url.Action("listcities", "city")" class="text-capitalize">@Localizer["list of cities"]</a></li>
    <li class="active text-capitalize">@Localizer["city editing"]</li>
</ol>

<section class="addrecord_s">
    <div class="container">
        <div class="row">
            <h4 class="text-center text-capitalize">@Localizer["city editing"]</h4>
        </div>
        <div class="row">
            <form asp-controller="City" asp-action="EditCity" method="post" asp-antiforgery="true">
                <input type="hidden" asp-for="Id" />

                <div class="col-md-12">
                    <div class="form-group">
                        <h5 class="text-capitalize"><label asp-for="Name"></label></h5>
                        <input type="text" class="form-control" asp-for="Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-default my_btn text-capitalize">@Localizer["save"]</button>
                </div>
            </form>
        </div>
    </div>
</section>

@section Scripts
{
    <script src="~/js/city.js" asp-append-version="true"></script>
}

EpamProject/EpamProject.WEB/Views/City/ListCities.cshtml
@model IPagedList<City>

@{
    ViewData["Title"] = @Localizer["list of cities"];
}

<ol class="breadcrumb">
    <li><a href="@Url.Action("profile", "manage")" class="text-capitalize">@Localizer["profile"]</a></li>
    <li class="active text-capitalize">@Localizer["list of cities"]</li>
</ol>

<section class="item_s">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                @Html.Partial("_Nav")
            </div>
            <div class="col-md-10">
                <h4 class="text-capitalize">@Localizer["tickets"]</h4>
                <div class="tickets_list">
                    <table class="table table-striped">
                        <tr>
                            <th class="text-capitalize">@Localizer["name"]</th>
                            <th class="text-capitalize"><a href="@Url.Action("addcity", "city")" class="ref_nav text-capitalize">@Localizer["add city"]</a></th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="text-capitalize">@item.Name</td>
                                <td class="text-capitalize">
                                    <a href="@Url.Action("listvenues", "venue", new { cityId = item.Id })" class="text-capitalize">@Localizer["list of venues"]</a>
                                    <a href="@Url.Action("editcity", "city", new { cityId = item.Id })" class="text-capitalize">@Localizer["edit"]</a>
                                    <a href="@Url.Action("removecity", "city", new { cityId = item.Id })" onclick="return confirm ('@Localizer["are you sure?"].Value')" class="text-capitalize">@Localizer["delete"]</a>
                                </td>
                            </tr>
                        }
                    </table>

                    <div class="pagination_s"><pager source="Model" /></div>
                </div>
            </div>
        </div>
    </div>
</section>