EpamProject/EpamProject.WEB/Controllers/SessionController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using EpamProject.WEB.Models.SessionViewModels;
using EpamProject.DAL.Entities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using EpamProject.BLL.Interfaces;
using System.IO;

namespace EpamProject.WEB.Controllers
{
    [Authorize(Roles = "Administrator, Moderator")]
    public class SessionController : Controller
    {
        IHostingEnvironment _appEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ICategoryService _categoryService;
        private readonly IEventService _eventService;
        private readonly ISessionService _sessionService;
        private readonly IOrderService _orderService;
        private readonly IRecordService _recordService;
        private readonly ITicketService _ticketService;
        private readonly ICityService _cityService;
        private readonly IVenueService _venueService;

        public SessionController(
            IHostingEnvironment appEnvironment, 
            ICategoryService categoryService, 
            IEventService eventService, 
            ISessionService sessionService,
            IOrderService orderService, 
            IRecordService recordService, 
            ITicketService ticketService,
            ICityService cityService,
            IVenueService venueService,
             UserManager<ApplicationUser> userManager, 
             SignInManager<ApplicationUser> signInManager)
        {
            _appEnvironment = appEnvironment;
            _userManager = userManager;
            _signInManager = signInManager;
            _categoryService = categoryService;
            _eventService = eventService;
            _sessionService = sessionService;
            _orderService = orderService;
            _recordService = recordService;
            _ticketService = ticketService;
            _cityService = cityService;
            _venueService = venueService;
        }

        [HttpGet]
        public IActionResult AddSession(int recordId)
        {
            var user = GetCurrentUserAsync();
            if (user.Result == null)
                return RedirectToAction("logoff", "account");

            var data = _sessionService.GetById(recordId);
            if (data == null)
                return NotFound();

            var model = new UpdateSessionModel()
            {
                RecordId = recordId
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddSession(IFormFile Poster, UpdateSessionModel model)
        {
            if (ModelState.IsValid)
            {
                var newSession = new Session();

                var currentCity = _cityService.GetById(model.CityId);
                if (currentCity == null)
                    return NotFound();

                var currentVenue = _venueService.GetById(model.VenueId);
                if (currentVenue == null)
                    return NotFound();

                if (!currentCity.Venues.Contains(currentVenue))
                    return NotFound();

                var data = _sessionService.GetById(model.RecordId);
                if (data == null)
                    return NotFound();

                if (Poster != null && Poster.Length > 0)
                {
                    var file = Poster;
                    var uploads = Path.Combine(_appEnvironment.WebRootPath, "images\\Posters");

                    if (file.Length > 0)
                    {
                        var fileName = Guid.NewGuid().ToString() + ".jpg";
                        var path = Path.Combine(uploads, fileName);

                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            file.CopyToAsync(fileStream);
                            newSession.VenueId = model.VenueId;
                            newSession.Date = model.Date;
                            newSession.Description = model.Description;
                            newSession.Poster = fileName;
                            newSession.RecordId = model.RecordId;
                        }
                    }
                }

                _sessionService.Create(newSession);
                return RedirectToAction("item", "home", new { recordId = newSession.RecordId });
            }
            else
            {
                return View("addsession", model);
            }
        }

        [HttpGet]
        public IActionResult EditSession(int sessionId)
        {
            var user = GetCurrentUserAsync();
            if (user.Result == null)
                return RedirectToAction("logoff", "account");

            var data = _sessionService.GetById(sessionId);
            if (data == null)
                return NotFound();

            var model = new UpdateSessionModel
            {
                RecordId = data.RecordId,
                VenueId = data.VenueId,
                Date = data.Date,
                Description = data.Description
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditSession(IFormFile Poster, UpdateSessionModel model)
        {
            if (ModelState.IsValid)
            {
                var data = _sessionService.GetById(model.RecordId);
                if (data == null)
                    return NotFound();

                var currentCity = _cityService.GetById(model.CityId);
                if (currentCity == null)
                    return NotFound();

                var currentVenue = _venueService.GetById(model.VenueId);
                if (currentVenue == null)
                    return NotFound();

                if (!currentCity.Venues.Contains(currentVenue))
                    return NotFound();

                if (Poster != null && Poster.Length > 0)
                {
                    var file = Poster;
                    var uploads = Path.Combine(_appEnvironment.WebRootPath, "images\\Posters");

                    if (file.Length > 0)
                    {
                        var fileName = Guid.NewGuid().ToString() + ".jpg";
                        var path = Path.Combine(uploads, fileName);

                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            file.CopyToAsync(fileStream);
                            data.Poster = fileName;
                        }
                    }
                }

                data.VenueId = model.VenueId;
                data.Date = model.Date;
                data.RecordId = model.RecordId;
                data.Description = model.Description;

                _sessionService.Update(data);
                return RedirectToAction("item", "home", new { recordId = data.RecordId });
            }
            else
            {
                return View("editsession", model);
            }
        }

        [HttpGet]
        public IActionResult RemoveSession(int sessionId)
        {
            var user = GetCurrentUserAsync();
            if (user.Result == null)
                return RedirectToAction("logoff", "account");

            var data = _sessionService.GetById(sessionId);
            if (data == null)
                return NotFound();

            if (data.Tickets == null)
            {
                _sessionService.Remove(data);
                return RedirectToAction("item", "home", new { recordId = data.RecordId });
            }
            else if (data.Tickets.Count == 0)
            {
                _sessionService.Remove(data);
                return RedirectToAction("item", "home", new { recordId = data.RecordId });
            }
            else
                return NotFound("Deleting is not possible, there are tickets for this session");
        }


        #region Helpers

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }

        #endregion
    }
}

EpamProject/EpamProject.WEB/Views/Session/AddSession.cshtml
@model UpdateSessionModel

@{
    ViewData["Title"] = @Localizer["session addition"];
}

<ol class="breadcrumb">
    <li><a href="@Url.Action("index", "home")" class="text-capitalize">@Localizer["home"]</a></li>
    <li class="active text-capitalize">@Localizer["session addition"]</li>
</ol>

<section class="addrecord_s">
    <div class="container">
        <div class="row">
            <h4 class="text-center text-capitalize">@Localizer["session addition"]</h4>
        </div>
        <div class="row">
            <form asp-controller="Session" asp-action="AddSession" method="post" asp-antiforgery="true" enctype="multipart/form-data">
                <input type="hidden" asp-for="RecordId" />

                <div class="col-md-4 col-md-offset-1">
                    <div class="form-group">
                        <h5 class="text-capitalize"><label asp-for="Poster"></label></h5>
                        <input asp-for="Poster" />
                    </div>
                    <div class="form-group">
                        <h5 class="text-capitalize">@Localizer["cities"]</h5>
                        <select class="custom_select" id="CityId" name="CityId"></select>
                        <span asp-validation-for="CityId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <h5 class="text-capitalize">@Localizer["venues"]</h5>
                        <select class="custom_select" id="VenueId" name="VenueId"></select>
                        <span asp-validation-for="VenueId" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="form-group">
                        <h5 class="text-capitalize"><label asp-for="Date"></label></h5>
                        <input type="datetime-local" class="form-control" asp-for="Date">
                        <span asp-validation-for="Date" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <h5 class="text-capitalize"><label asp-for="Description"></label></h5>
                        <textarea style="resize: none;" asp-for="Description" class="form-control" rows="3"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-default my_btn text-capitalize">@Localizer["submit"]</button>
                </div>
            </form>
        </div>
    </div>
</section>

@section Scripts
{
    <script src="~/js/sessionsAPI.js" asp-append-version="true"></script>
}

EpamProject/EpamProject.WEB/Views/Session/EditSession.cshtml
@model UpdateSessionModel

@{
    ViewData["Title"] = @Localizer["session editing"];
}

<ol class="breadcrumb">
    <li><a href="@Url.Action("index", "home")" class="text-capitalize">@Localizer["home"]</a></li>
    <li class="active text-capitalize">@Localizer["session editing"]</li>
</ol>

<section class="addrecord_s">
    <div class="container">
        <div class="row">
            <h4 class="text-center text-capitalize">@Localizer["session editing"]</h4>
        </div>
        <div class="row">
            <form asp-controller="Session" asp-action="EditSession" method="post" asp-antiforgery="true" enctype="multipart/form-data">
                <input type="hidden" asp-for="RecordId" />

                <div class="col-md-4 col-md-offset-1">
                    <div class="form-group">
                        <h5 class="text-capitalize"><label asp-for="Poster"></label></h5>
                        <input asp-for="Poster" />
                    </div>
                    <div class="form-group">
                        <h5 class="text-capitalize">@Localizer["cities"]</h5>
                        <select class="custom_select" id="CityId" name="CityId"></select>
                        <span asp-validation-for="CityId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <h5 class="text-capitalize">@Localizer["venues"]</h5>
                        <select class="custom_select" id="VenueId" name="VenueId"></select>
                        <span asp-validation-for="VenueId" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="form-group">
                        <h5 class="text-capitalize"><label asp-for="Date"></label></h5>
                        <input type="datetime-local" class="form-control" asp-for="Date">
                        <span asp-validation-for="Date" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <h5 class="text-capitalize"><label asp-for="Description"></label></h5>
                        <textarea style="resize: none;" asp-for="Description" class="form-control" rows="3"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-default my_btn text-capitalize">@Localizer["save"]</button>
                </div>
            </form>
        </div>
    </div>
</section>

@section Scripts
{
    <script src="~/js/sessionsAPI.js" asp-append-version="true"></script>
}